-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

-- Enums
CREATE TYPE user_role AS ENUM ('PARENT', 'CHILD');
CREATE TYPE parent_child_link_status AS ENUM ('PENDING', 'ACTIVE', 'REVOKED');
CREATE TYPE profile_mode AS ENUM ('STANDARD', 'DEMO');
CREATE TYPE difficulty_level AS ENUM ('SIMPLE', 'ADVANCED');
CREATE TYPE parent_gate_mode AS ENUM ('HOLD', 'MATH_TASK');
CREATE TYPE cosmetic_kind AS ENUM ('FUR', 'ACCESSORY');
CREATE TYPE pet_name_status AS ENUM ('APPROVED', 'FLAGGED');

CREATE TYPE period_status AS ENUM ('ACTIVE', 'COMPLETED');
CREATE TYPE plan_status AS ENUM ('DRAFT', 'CONFIRMED');

CREATE TYPE wallet_kind AS ENUM ('SPENDABLE', 'SAVINGS', 'FROZEN');
CREATE TYPE transaction_event_type AS ENUM (
    'START_GRANT',
    'DAILY_INCOME',
    'STREAK_BONUS',
    'PERIOD_GRANT',
    'QUEST_REWARD',
    'PARENT_TASK_REWARD',
    'PURCHASE',
    'SAVINGS_DEPOSIT',
    'SAVINGS_WITHDRAWAL',
    'FROST_DEPOSIT',
    'FROST_WITHDRAWAL',
    'FROST_BONUS',
    'GOAL_REDEMPTION',
    'PET_EVENT_PAYMENT'
);

CREATE TYPE frost_chest_status AS ENUM ('ACTIVE', 'WITHDRAWN_EARLY', 'COLLECTED');

CREATE TYPE item_kind AS ENUM ('NEED', 'WANT', 'ARTIFACT');
CREATE TYPE rarity_kind AS ENUM ('COMMON', 'RARE', 'EPIC', 'LEGENDARY');

CREATE TYPE assignment_origin AS ENUM ('SYSTEM', 'PARENT');
CREATE TYPE assignment_status AS ENUM (
    'AVAILABLE', 'IN_PROGRESS', 'AWAITING_PARENT', 'VERIFIED', 'COMPLETED', 'CANCELLED'
);
CREATE TYPE step_outcome AS ENUM ('SUCCESS', 'RECOVERABLE_ERROR');

CREATE TYPE goal_status AS ENUM ('ACTIVE', 'PAUSED', 'ACHIEVED', 'REDEEMED', 'CANCELLED');

CREATE TYPE pet_event_status AS ENUM ('ACTIVE', 'RESOLVED');
